name: Build

on:  
  push:
    branches: [ main ]

jobs:  
  build:    
    runs-on: [self-hosted, windows]
    
    steps:
      - name: cmd
        env: # Set the secret as an input
          super_secret: ${{ secrets.MYSEC }}
        run: 
          echo "$env:super_secret"

# Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.MYSEx }}
        if:  env.WHO_TO_TRUST == 'MySec'
        run: echo "I know what the secret token is!"