name: Build

on:  
  push:
    branches: [ main ]

jobs:  
  build:    
    runs-on: [self-hosted, windows]
    
    steps:      
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        env: 
          super_secret: ${{ secrets.MY }}
        run: |
          dotnet build ./${{ secrets.NugetApiKey }}/SelfHostRunner.sln -c Release
