name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: actions/setup-dotnet@2

      - name: Build Solution
        env:
          super_secret: ${{ secrets.MY }}
        run: |
          dotnet build ./$env:super_secret/SelfHostRunner.sln -c Release

      - name: Clear runner
        if: ${{ always() }}
        run: |
          rm ./* -r -force