name: Build

on:  
  push:
    branches: [ main ]

jobs:  
  build:    
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Hello world action
        env: # Set the secret as an input
          super_secret: ${{ secrets.TOPSECRET }}
        run: 
          echo "$env:SUPER_SECRET"