name: Build

on:  
  push:
    branches: [ main ]

jobs:  
  build:    
    runs-on: [self-hosted, windows]
    
    steps:
      - uses: actions/checkout@v2

      - name: Hello world action
        with: # Set the secret as an input
          super_secret: ${{ secrets.TOPSECRET }}
        env: # Set the secret as an input
          super_secret: ${{ secrets.TOPSECRET }}
        run: 
          echo $super_secret       

 #     - name: Setup MSBuild
 #       uses: microsoft/setup-msbuild@v1

#      - name: Build Solution
#        run: |
#          dotnet build ./${{ secrets.TOPSECRET }}/SelfHostRunner.sln -c Release