name: Build

on:  
  push:
    branches: [ main ]

jobs:  
  build:    
    runs-on: [self-hosted, windows]
    
    steps:      
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: |
          dotnet build ./SelfHostRunner/SelfHostRunner.sln -c Release

      - name: Build Solution
        run: |
          echo $RUNNER_WORKSPACE